site_name: inskewl
site_description: Dokumentasjon for inskewl
site_url: https://mathiasdevelopes.github.io/inskewl/
repo_url: https://github.com/MathiasDevelopes/inskewl

theme:
  name: mkdocs

nav:
  - Hjem: index.md
  - Fraværskalkulator: fravaerskalkulator/demo.md

extra_javascript:
  - assets/attendance-calculator-demo.js
