import { z } from "zod";
import { transformISODate } from "../../utils/parsing";

export const LocaleSchema = z.object({
  country: z.string(),
  language: z.string(),
  locale: z.string().meta({
    description: "ISO 639 + ISO 3166 locale tag.",
  }),
});

export const UserSchema = z.object({
  username: z.any(),
  displayName: z.string(),
  givenName: z.string(),
  familyName: z.string(),
  roles: z.array(z.string()),
  academicYearId: z.number(),
  facultyId: z.any(),
  localId: z.any(),
  learnerId: z.number(),
  userInfoId: z.number(),
  locale: LocaleSchema,
  schoolName: z.string(),
  tenant: z.number(),
});

export type User = z.infer<typeof UserSchema>;

export const PersonalInfoSchema = z.object({
  vsware_type: z.string(),
  displayName: z.null(),
  id: z.number(),
  userInfoId: z.number(),
  photoId: z.string(),
  givenName: z.string(),
  familyName: z.string(),
  preferredGivenName: z.null(),
  address: z.null(),
  boarderIndicator: z.null(),
  religionName: z.null(),
  countryCode: z.string(),
  mobilePhone: z.string(),
  homePhone: z.null(),
  email: z.email(),
  classGroupId: z.null(),
  otherId: z.null(),
  leavingDestination: z.null(),
  leavingReason: z.null(),
  destinationLEACode: z.null(),
  destinationEstablishment: z.null(),
  middleNames: z.null(),
  birthDate: z.iso.date().transform(transformISODate),
  gender: z.string(),
  religionAffiliationCode: z.null(),
  startDate: z.iso.date().transform(transformISODate),
  endDate: z.iso.date().transform(transformISODate),
  localId: z.null(),
  photoURL: z.string(),
  showPhone: z.null(),
  showEmail: z.null(),
  showFullName: z.null(),
  mainTeacherMobilePhone: z.null(),
  mainTeacherEmail: z.null(),
  mainTeacherFirstName: z.null(),
  mainTeacherPreferredGivenName: z.null(),
  mainTeacherLastName: z.null(),
  lockerNumber: z.null(),
  emailOptIn: z.null(),
  mainTeacherWorkforcePersonalId: z.number(),
  leftEarlyReason: z.null(),
  legalGivenName: z.string(),
  legalFamilyName: z.string(),
  previousSchoolTypeEnum: z.null(),
  travellerCode: z.null(),
  previousSchoolRollNo: z.null(),
  countryOfBirthEnum: z.null(),
  nationalityEnum: z.null(),
  username: z.null(),
  tenant: z.number(),
  previousSchoolName: z.null(),
  workforcePersonalId: z.number(),
  classGroupName: z.null(),
  nextOfKinPhoneNumber: z.null(),
  nextOfKin: z.null(),
  language: z.null(),
  learnerInfo: z.null(),
  accountActive: z.null(),
  basisOfAdmission: z.null(),
  nationalIdentityNumber: z.null(),
  nationalIdentityNumberType: z.null(),
  adultRight: z.boolean(),
  admissionRight: z.string(),
  affiliation: z.string(),
  bilingualInstruction: z.null(),
  citizenshipId: z.null(),
  exceptionalCircumstances: z.null(),
  externalCandidate: z.boolean(),
  firstChoiceForm: z.string(),
  hasConfidentialInfo: z.boolean(),
  isMainSchool: z.boolean(),
  languageExemption: z.null(),
  learnerPersonalId: z.number(),
  motherTongueId: z.null(),
  motherTongueInstruction: z.null(),
  municipality: z.null(),
  physicalEducationExemption: z.null(),
  samiInstruction: z.null(),
  secondChoiceForm: z.string(),
  specialNorwegianInstruction: z.null(),
  individualDecisions: z.null(),
  programmeArea: z.null(),
  programmeAreaId: z.number(),
  schoolEnrolments: z.null(),
  residentialAddress: z.null(),
  guest: z.boolean(),
  reasonCodeAdded: z.boolean(),
  feideName: z.string(),
  inAdultEducation: z.boolean(),
  adaptedLanguageEducation: z.boolean(),
  partTime: z.null(),
  immutableUserId: z.string(),
  endCause: z.null(),
  completionCode: z.null(),
  isSecondSchool: z.boolean(),
  vocationalProgrammeArea: z.null(),
  exchangeDetails: z.null(),
  campusId: z.null(),
  duf: z.null(),
  leftEarly: z.boolean(),
  learnerId: z.object({
    typeId: z.number(),
    userInfoId: z.number(),
    immutableUserId: z.uuid(),
  }),
  leavingEarlyInFuture: z.boolean(),
});

export type PersonalInfo = z.infer<typeof PersonalInfoSchema>;
