/**
 * @file Automatically generated by barrelsby.
 */

export * from "./assessment";
export * from "./attendance";
export * from "./calendar";
export * from "./events";
export * from "./exams";
export * from "./inbox";
export * from "./login-page";
export * from "./school";
export * from "./tenant";
export * from "./timetable";
export * from "./user";
